### ISSUE TITLE
Error caused by some recent update to plot recipes

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/Makie.jl#1083]
https://github.com/JuliaGeometry/MeshViz.jl/issues/13

Did anything change internally, which was perhaps released as a patch release?

**Comment by jkrumbiegel** [comment]
This was caused by a patch release to GridLayoutBase and fixed with a patch release to Makie, so updating Makie fixes the problem.

**Comment by juliohm** [comment]
I am trying it on a fresh environment but the error persists:

```julia
] activate --temp
] add Meshes MeshViz GLMakie
] status -m

      Status `/tmp/jl_2WC9Jz/Manifest.toml`
  [621f4979] AbstractFFTs v1.0.1
  [79e6a3ab] Adapt v3.3.1
  [27a7e980] Animations v0.4.1
  [4fba245c] ArrayInterface v3.1.17
  [13072b0f] AxisAlgorithms v1.0.0
  [fa961155] CEnum v0.4.1
  [324d7699] CategoricalArrays v0.10.0
  [d360d2e6] ChainRulesCore v0.10.9
  [7a955b69] CircularArrays v1.2.0
  [a2cac450] ColorBrewer v0.4.0
  [35d6a980] ColorSchemes v3.12.1
  [3da002f7] ColorTypes v0.11.0
  [c3611d14] ColorVectorSpace v0.9.5
  [5ae59095] Colors v0.12.8
  [34da2185] Compat v3.31.0
  [d38c429a] Contour v0.5.7
  [a8cc5b0e] Crayons v4.0.4
  [9a962f9c] DataAPI v1.7.0
  [864edb3b] DataStructures v0.18.9
  [e2d170a0] DataValueInterfaces v1.0.0
  [b4f34e82] Distances v0.10.3
  [31c24e10] Distributions v0.25.6
  [ffbed154] DocStringExtensions v0.8.5
  [da5c29d0] EllipsisNotation v1.1.0
  [c87230d0] FFMPEG v0.4.1
  [7a1cc6ca] FFTW v1.4.3
  [5789e2e9] FileIO v1.10.1
  [1a297f60] FillArrays v0.11.7
  [53c48c17] FixedPointNumbers v0.8.4
  [59287772] Formatting v0.4.2
  [b38be410] FreeType v4.0.0
  [663a7486] FreeTypeAbstraction v0.9.1
  [f7f18e0c] GLFW v3.4.1
  [e9467ef8] GLMakie v0.3.4
  [5c1252a2] GeometryBasics v0.3.12
  [a2bd30eb] Graphics v1.1.0
  [3955a311] GridLayoutBase v0.5.5
  [42e2da0e] Grisu v1.0.2
  [615f187c] IfElse v0.1.0
  [a09fc81d] ImageCore v0.9.1
  [82e4d734] ImageIO v0.5.6
  [9b13fd28] IndirectArrays v0.5.1
  [d25df0c9] Inflate v0.1.2
  [a98d9a8b] Interpolations v0.13.2
  [8197267c] IntervalSets v0.5.3
  [f1662d9f] Isoband v0.1.1
  [c8e1da08] IterTools v1.3.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.3.0
  [682c06a0] JSON v0.21.1
  [5ab0869b] KernelDensity v0.6.3
  [2ab3a3ac] LogExpFunctions v0.2.4
  [1914dd2f] MacroTools v0.5.6
  [ee78f7c6] Makie v0.13.14
  [dbb5928d] MappedArrays v0.4.0
  [7eb4fadd] Match v1.1.0
  [7269a6da] MeshIO v0.4.7
  [9ecf9c4f] MeshViz v0.1.9
  [eacbb407] Meshes v0.16.10
  [e1d29d7a] Missings v1.0.0
  [66fc600b] ModernGL v1.1.2
  [e94cdb99] MosaicViews v0.3.3
  [77ba4419] NaNMath v0.3.5
  [b8a86587] NearestNeighbors v0.4.9
  [f09324ee] Netpbm v1.0.2
  [510215fc] Observables v0.4.0
  [6fe1bfb0] OffsetArrays v1.10.0
  [bac558e1] OrderedCollections v1.4.1
  [90014a1f] PDMats v0.11.1
  [f57f5aa1] PNGFiles v0.3.7
  [19eb6ba3] Packing v0.4.1
  [5432bcbf] PaddedViews v0.5.8
  [69de0a69] Parsers v1.1.0
  [eebad327] PkgVersion v0.1.1
  [995b91a9] PlotUtils v1.0.10
  [647866c9] PolygonOps v0.1.1
  [21216c6a] Preferences v1.2.2
  [92933f4c] ProgressMeter v1.7.1
  [1fd47b50] QuadGK v2.4.1
  [c84ed2f1] Ratios v0.4.0
  [3cdcf5f2] RecipesBase v1.1.1
  [189a3867] Reexport v1.1.0
  [74f56ac7] ReferenceFrameRotations v1.0.0
  [ae029012] Requires v1.1.3
  [79098fc4] Rmath v0.7.0
  [65257c39] ShaderAbstractions v0.2.7
  [992d4aef] Showoff v1.0.3
  [73760f76] SignedDistanceFields v0.4.0
  [699a6c99] SimpleTraits v0.9.3
  [a2af1166] SortingAlgorithms v1.0.0
  [276daf66] SpecialFunctions v1.5.1
  [cae243ae] StackViews v0.1.1
  [aedffcd0] Static v0.2.5
  [90137ffa] StaticArrays v1.2.4
  [82ae8749] StatsAPI v1.0.0
  [2913bbd2] StatsBase v0.33.8
  [4c63d2b9] StatsFuns v0.9.8
  [09ab397b] StructArrays v0.5.1
  [856f2bd8] StructTypes v1.7.2
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.4.4
  [62fd8b95] TensorCore v0.1.1
  [731e570b] TiffImages v0.4.0
  [1cfade01] UnicodeFun v0.4.1
  [efce3f68] WoodburyMatrices v0.5.3
  [6e34b625] Bzip2_jll v1.0.8+0
  [83423d85] Cairo_jll v1.16.1+0
  [5ae413db] EarCut_jll v2.1.5+1
  [2e619515] Expat_jll v2.2.10+0
  [b22a6f82] FFMPEG_jll v4.4.0+0
  [f5851436] FFTW_jll v3.3.9+7
  [a3f928ae] Fontconfig_jll v2.13.93+0
  [d7e528f0] FreeType2_jll v2.10.4+0
  [559328eb] FriBidi_jll v1.0.10+0
  [0656b61e] GLFW_jll v3.3.5+0
  [78b55507] Gettext_jll v0.21.0+0
  [7746bdde] Glib_jll v2.68.1+0
  [3b182d85] Graphite2_jll v1.3.14+0
  [2e76f6c2] HarfBuzz_jll v2.8.1+0
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+2
  [c1c5ebd0] LAME_jll v3.100.1+0
  [dd4b983a] LZO_jll v2.10.1+0
  [e9f186c6] Libffi_jll v3.2.2+0
  [d4300ac3] Libgcrypt_jll v1.8.7+0
  [7e76a0d4] Libglvnd_jll v1.3.0+3
  [7add5ba3] Libgpg_error_jll v1.42.0+0
  [94ce4f54] Libiconv_jll v1.16.1+1
  [4b2f31a3] Libmount_jll v2.35.0+0
  [38a345b3] Libuuid_jll v2.36.0+0
  [856f044c] MKL_jll v2021.1.1+1
  [e7412a2a] Ogg_jll v1.3.5+0
  [458c3c95] OpenSSL_jll v1.1.10+0
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [91d4177d] Opus_jll v1.3.2+0
  [2f80f16e] PCRE_jll v8.44.0+0
  [30392449] Pixman_jll v0.40.1+0
  [f50d1b31] Rmath_jll v0.3.0+0
  [02c8fc9c] XML2_jll v2.9.12+0
  [aed1982a] XSLT_jll v1.1.34+0
  [4f6342f7] Xorg_libX11_jll v1.6.9+4
  [0c0b7dd1] Xorg_libXau_jll v1.0.9+4
  [935fb764] Xorg_libXcursor_jll v1.2.0+4
  [a3789734] Xorg_libXdmcp_jll v1.1.3+4
  [1082639a] Xorg_libXext_jll v1.3.4+4
  [d091e8ba] Xorg_libXfixes_jll v5.0.3+4
  [a51aa0fd] Xorg_libXi_jll v1.7.10+4
  [d1454406] Xorg_libXinerama_jll v1.1.4+4
  [ec84b674] Xorg_libXrandr_jll v1.5.2+4
  [ea2f1a96] Xorg_libXrender_jll v0.9.10+4
  [14d82f49] Xorg_libpthread_stubs_jll v0.1.0+3
  [c7cfdc94] Xorg_libxcb_jll v1.13.0+3
  [c5fb5394] Xorg_xtrans_jll v1.4.0+3
  [9a68df92] isoband_jll v0.2.2+0
  [0ac62f75] libass_jll v0.15.1+0
  [f638f0a6] libfdk_aac_jll v2.0.2+0
  [b53b4c65] libpng_jll v1.6.38+0
  [f27f6e37] libvorbis_jll v1.3.7+0
  [1270edf5] x264_jll v2021.5.5+0
  [dfaa095f] x265_jll v3.5.0+0
  [0dad84c5] ArgTools
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8bb1440f] DelimitedFiles
  [8ba89e20] Distributed
  [f43a241f] Downloads
  [9fa8497b] Future
  [b77e0a4c] InteractiveUtils
  [4af54fe1] LazyArtifacts
  [b27032c2] LibCURL
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions
  [44cfe95a] Pkg
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays
  [10745b16] Statistics
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML
  [a4e569a6] Tar
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll
  [deac9b47] LibCURL_jll
  [29816b5a] LibSSH2_jll
  [c8ffd9c3] MbedTLS_jll
  [14a3606d] MozillaCACerts_jll
  [83775a58] Zlib_jll
  [8e850ede] nghttp2_jll
  [3f19e933] p7zip_jll
```

**Comment by SimonDanisch** [comment]
```
[e9467ef8] GLMakie v0.3.4
[ee78f7c6] Makie v0.13.14
```
You need `Makie@0.14.2 GLMakie@0.4.2` ... I guess MeshViz doesn't allow 0.14 yet?

@jkrumbiegel maybe we really need to retro bound the GridLayout version, since that makes older version buggy..

**Comment by juliohm** [comment]
I bumped the version in the Project.toml and the issue is solved. Will trigger a patch release 👍🏽
