### ISSUE TITLE
Projections of the earth in the examples on the front page

### ISSUE THREAD

**Issue by jaakkor2** [JuliaPlots/Makie.jl#137]
Looking at the examples on https://github.com/JuliaPlots/Makie.jl , 

First earth example from
https://gist.github.com/SimonDanisch/8f5489cffaf6b89c9a3712ba3eb12a84
simplified and with lighting adjusted (current documentation does not say too much about the light attribute :) )
```
using Makie, FileIO, Colors
earth = load(download("https://svs.gsfc.nasa.gov/vis/a000000/a002900/a002915/bluemarble-2048.png"));
scene = Scene(resolution = (500, 500), color = :black)
m = GLNormalUVMesh(Sphere(Point3f0(0), 1f0), 60)
light = Vec{3,Float32}[[1.0, 1.0, 1.0], [0.1, 0.1, 0.1], [0.9, 0.9, 0.9], [0.0, -20.0, 0.0]]
Makie.mesh(m, color = earth, light = light)
```
Antarctica looks big 
![antarctica1](https://user-images.githubusercontent.com/7318249/45255115-c5c5e000-b382-11e8-8ac6-30eae6af6ceb.png)

Antarctica should look like this (takes from Wikipedia)
![image](https://user-images.githubusercontent.com/7318249/45255310-df682700-b384-11e8-95f5-5a275ec22923.png)
https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Antarctica_%28orthographic_projection%29.svg/250px-Antarctica_%28orthographic_projection%29.svg.png

This example is a nice one
https://gist.github.com/SimonDanisch/58cb1050581658859f7a5df51fa1e5a1#file-earth-jl
but it has two problems
1)
Projection of the tempeture map has the same projection error as above.
2)
The precipitation is not matching the temperature map, but is 90 deg rotated and scaling is distorted
![earth](https://user-images.githubusercontent.com/7318249/45255299-a16b0300-b384-11e8-88aa-0f9ac876e709.png)

These are low priority, but since these are on the front page, I thought to file an issue.

Also, gists as far as I know do not accept PRs to update them to Julia v1.0.

**Comment by mkborregaard** [comment]
I think this is because of https://github.com/JuliaPlots/Makie.jl/issues/205

**Comment by AshtonSBradley** [comment]
trying another equirectangular projection test:
```julia
using Makie, FileIO, Colors, GeometryTypes
scene = Scene(resolution = (500, 500), color = :black)
m = GLNormalUVMesh(Sphere(Point3f0(0), 1f0), 60)
moon = load(download("https://svs.gsfc.nasa.gov/vis/a000000/a004600/a004675/phases.0001_print.jpg"))
mesh(m, color = moon)
```
there is quite a lot of polar distortion in the image. Craters are elliptical: 

![screen shot 2018-11-04 at 11 28 55 am](https://user-images.githubusercontent.com/24194258/47957936-da41f400-e024-11e8-866b-317a3a7be54c.png)

**Comment by AshtonSBradley** [comment]
ok, seems to have something to do with the coordinate spacing. I if I adapt the image on a sphere example, everything works:
```julia
using Makie, FileIO, Colors, GeometryTypes

linspace(a,b,n) = LinRange(a,b,n) |> Vector
n = 512
θ = linspace(0,pi,n)
φ = linspace(0,2*pi,2*n)
x = [cos(φ)*sin(θ) for θ in θ, φ in φ]
y = [sin(φ)*sin(θ) for θ in θ, φ in φ]
z = [cos(θ) for θ in θ, φ in φ]
pts = vec(Point3f0.(x, y, z))
moon = load(download("https://svs.gsfc.nasa.gov/vis/a000000/a004600/a004675/phases.0001_print.jpg"));
surface(x, y, z, color = moon)
```

![screen shot 2018-11-04 at 11 47 09 am](https://user-images.githubusercontent.com/24194258/47958027-66551b00-e027-11e8-8365-0122bcb51b7b.png)

**Comment by AshtonSBradley** [comment]
@SimonDanisch the distortion seems to be traceable to the way the sphere points are sampled by `HyperSphere`. Does this function generate an equirectangular coordinate grid for the 3-sphere? Should it be doing something like the image on a surface example adapted above?

**Comment by mkborregaard** [comment]
So the error is in the code wrapping the color on a spherical mesh. Where is that color defined in Makie?

**Comment by SimonDanisch** [comment]
It's basically here:
https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/src/decompose.jl#L367
And here:
https://github.com/JuliaGeometry/GeometryTypes.jl/blob/master/src/decompose.jl#L381
(uv coordinates are in 0..1 mapping to the coordinates of the image)

**Comment by mkborregaard** [comment]
But `decompose` works, right? Look at my image above - the points are correctly placed but the underlying heatmap isn't (or is it the other way around)? The "North pole" convergence of the `decompose` points are at the points that correspond to longitude-latitude `(0, 0)`, the South Pole at `(180, 0)` on the heatmap. 
But the correspondence should be at `(_, 90)` and `(_, -90)` (where `_` corresponds to any value as the longitudes collapse in the poles).

**Comment by SimonDanisch** [comment]
The UV map seems pretty wrong (`decompose(UV, Sphere(...))`)

**Comment by SimonDanisch** [comment]
This works:
```Julia
uv = [UV{Float32}(φ, θ) for θ in ux, φ in ux]
f = decompose(Face{3, GLIndex}, SimpleRectangle(0, 0, 1, 1), (n, n))
m = GLNormalUVMesh(vertices = pts, faces = f, texturecoordinates = vec(uv))
scene = mesh(m, color = moon, shading = false)
```
Maybe that's how I should define the decompose for sphere

**Comment by SimonDanisch** [comment]
Although that's still inconsistent with surface:
```Julia
![image](https://user-images.githubusercontent.com/1010467/47991599-eabca200-e0ea-11e8-8586-db4cd8909e9a.png)
```

**Comment by SimonDanisch** [comment]
Thanks everyone, I think this is fixed now with https://github.com/JuliaGeometry/GeometryTypes.jl/pull/158


```Julia
using Makie, FileIO, Colors
earth = load(download("https://svs.gsfc.nasa.gov/vis/a000000/a002900/a002915/bluemarble-2048.png"));
scene = Scene(resolution = (500, 500), color = :black)
m = GLNormalUVMesh(Sphere(Point3f0(0), 1f0), 60)
light = Vec{3,Float32}[[1.0, 1.0, 1.0], [0.1, 0.1, 0.1], [0.9, 0.9, 0.9], [0.0, -20.0, 0.0]]
Makie.mesh(m, color = earth, shading = false)
```
![earth](https://user-images.githubusercontent.com/1010467/47995813-da122900-e0f6-11e8-8a21-8c45979c1577.gif)

**Comment by mkborregaard** [comment]
Awesome, you're a wizard!

**Comment by mkborregaard** [comment]
Note that this does not completely resolve the issue with the points decomposition:
<img width="710" alt="skaermbillede 2018-11-05 kl 12 48 00" src="https://user-images.githubusercontent.com/8429802/47996589-53ab1680-e0f9-11e8-807a-c1c53f479df9.png">
Note the polar position of the points wrongly at (0,0) and the clearly misplaced rainy belt over Sahara. The bar heights could be something in the meshscatter function but at least the point decomposition is not consistent with that of a globe.

**Comment by mkborregaard** [comment]
For info, the world-clim precipitation layer is only defined over land, so the correct projection would put all the flat bars over the ocean.

**Comment by SimonDanisch** [comment]
Yeah the uv look up code needs to be adapted for sampling the precipitation:
![test](https://user-images.githubusercontent.com/1010467/48001864-1bf89a80-e10a-11e8-8ca1-acb97ff29fef.gif)

**Comment by mkborregaard** [comment]
Do you mean in the example or in GeometryTypes?

**Comment by SimonDanisch** [comment]
The example needs an update ;)

**Comment by mkborregaard** [comment]
OK, so you essentially just fixed the `to_msize` function? I wouldn't mind adding this unless you've essentially already done it for your plot above.

**Comment by SimonDanisch** [comment]
Yeah it's fixed ;) https://github.com/JuliaPlots/Makie.jl/blob/master/examples/bigdata.jl#L2 needed some julia 1.0 updates as well!

**Comment by mkborregaard** [comment]
Oh great. Yeah I'd fixed the other things locally because I wanted to update this example, that was how I fell over this to begin with.

**Comment by mkborregaard** [comment]
So, this can be closed I guess?
