### ISSUE TITLE
Test Makie failing in Julia 1.1

### ISSUE THREAD

**Issue by myrddin89** [JuliaPlots/Makie.jl#306]
I installed Makie 0.9.2 and I run `test Makie` on the REPL. The test fails on `mesh scatter_function` with 
`LoadError: MethodError: no method matching light_calc(::Observables.Observable{Bool})`
 
Here the log:

```
running meshscatter_function
ERROR: LoadError: MethodError: no method matching light_calc(::Observables.Observable{Bool})
Closest candidates are:
  light_calc(::Bool) at ~/.julia/packages/GLMakie/rAuGK/src/GLVisualize/visualize/surface.jl:53
Stacktrace:
 [1] meshparticle(::Tuple{Observables.Observable{GeometryTypes.HyperSphere{3,Float32}},Observables.Observable{Array{Point{3,Float32},1}}}, ::GLMakie.GLAbstraction.Style{:default}, ::Dict{Symbol,Any}) at ~/.julia/packages/GLMakie/rAuGK/src/GLAbstraction/GLUtils.jl:179
 [2] _default(::Tuple{Observables.Observable{GeometryTypes.HyperSphere{3,Float32}},Observables.Observable{Array{Point{3,Float32},1}}}, ::GLMakie.GLAbstraction.Style{:default}, ::Dict{Symbol,Any}) at ~/.julia/packages/GLMakie/rAuGK/src/GLVisualize/visualize/particles.jl:188
 [3] default(::Any, ::Any, ::Any) at ~/.julia/packages/GLMakie/rAuGK/src/GLVisualize/visualize_interface.jl:4
 [4] visualize(::Any, ::GLMakie.GLAbstraction.Style{:default}, ::Dict{Symbol,Any}) at ~/.julia/packages/GLMakie/rAuGK/src/GLVisualize/visualize_interface.jl:21
 [5] (::getfield(GLMakie, Symbol("##61#63")){Scene,MeshScatter{...}})(::Dict{Symbol,Any}) at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:123
 [6] (::getfield(GLMakie, Symbol("##47#50")){getfield(GLMakie, Symbol("##61#63")){Scene,MeshScatter{...}},GLMakie.Screen,Scene,MeshScatter{...}})() at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:40
 [7] get!(::getfield(GLMakie, Symbol("##47#50")){getfield(GLMakie, Symbol("##61#63")){Scene,MeshScatter{...}},GLMakie.Screen,Scene,MeshScatter{...}}, ::Dict{UInt64,GLMakie.GLAbstraction.RenderObject}, ::UInt64) at ./dict.jl:453
 [8] cached_robj!(::getfield(GLMakie, Symbol("##61#63")){Scene,MeshScatter{...}}, ::GLMakie.Screen, ::Scene, ::MeshScatter{...}) at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:33
 [9] draw_atomic at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:112 [inlined]
 [10] insert!(::GLMakie.Screen, ::Scene, ::MeshScatter{...}) at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:105
[11] insertplots!(::GLMakie.Screen, ::Scene) at ~/.julia/packages/GLMakie/rAuGK/src/screen.jl:51
 [12] display(::GLMakie.Screen, ::Scene) at ~/.julia/packages/GLMakie/rAuGK/src/screen.jl:89
 [13] scene2image at ~/.julia/packages/GLMakie/rAuGK/src/gl_backend.jl:64 [inlined]
 [14] backend_show at ~/.julia/packages/GLMakie/rAuGK/src/gl_backend.jl:69 [inlined]
 [15] show(::IOContext{IOStream}, ::MIME{Symbol("image/png")}, ::Scene) at ~/.julia/packages/AbstractPlotting/KIwn9/src/display.jl:62
 [16] #689 at ~/.julia/packages/AbstractPlotting/KIwn9/src/display.jl:125 [inlined]
 [17] #open#310(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(AbstractPlotting, Symbol("##689#690")){Scene}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:369
 [18] open at ./iostream.jl:367 [inlined]
 [19] save at ~/.julia/packages/AbstractPlotting/KIwn9/src/display.jl:124 [inlined]
 [20] save_media at ~/.julia/packages/MakieGallery/ioVlA/src/io.jl:3 [inlined]
 [21] (::getfield(MakieGallery, Symbol("##99#101")){Tuple{Int64,Int64},String})(::MakieGallery.CellEntry, ::Scene) at ~/.julia/packages/MakieGallery/ioVlA/src/io.jl:221
 [22] (::getfield(MakieGallery, Symbol("##78#79")){Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#100")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#100")){String}}}},getfield(MakieGallery, Symbol("##99#101")){Tuple{Int64,Int64},String}})(::MakieGallery.CellEntry) at ~/.julia/packages/MakieGallery/ioVlA/src/database.jl:551
 [23] #enumerate_examples#61(::Int64, ::Nothing, ::Function, ::getfield(MakieGallery, Symbol("##78#79")){Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#100")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#100")){String}}}},getfield(MakieGallery, Symbol("##99#101")){Tuple{Int64,Int64},String}}) at ~/.julia/packages/MakieGallery/ioVlA/src/database.jl:498
 [24] #enumerate_examples at ./none:0 [inlined]
 [25] #eval_examples#77 at ~/.julia/packages/MakieGallery/ioVlA/src/database.jl:549 [inlined]
 [26] #eval_examples at ./none:0 [inlined]
 [27] #record_examples#98(::Tuple{Int64,Int64}, ::Bool, ::Bool, ::Function, ::String) at ~/.julia/packages/MakieGallery/ioVlA/src/io.jl:214
 [28] record_examples(::String) at ~/.julia/packages/MakieGallery/ioVlA/src/io.jl:198
 [29] top-level scope at none:0
 [30] include at ./boot.jl:326 [inlined]
 [31] include_relative(::Module, ::String) at ./loading.jl:1038
 [32] include(::Module, ::String) at ./sysimg.jl:29
 [33] include(::String) at ./client.jl:403
 [34] top-level scope at none:0
in expression starting at ~/.julia/packages/Makie/6qGoc/test/runtests.jl:20
ERROR: Package Makie errored during testing
```

**Comment by SimonDanisch** [comment]
`free GLMakie AbstractPlotting Makie; up GLMakie AbstractPlotting Makie` should fix it!

**Comment by myrddin89** [comment]
I tried this and also removing/reinstalling packages but the test still fails on `meshscatter_function`.

Here is the full log:

```
   Testing Makie
 Resolving package versions...
    Status `/var/folders/5d/lhr75bmj5gj212_cy3_xtyc40000gn/T/tmpUFqRZu/Manifest.toml`
  [621f4979] AbstractFFTs v0.3.2
  [537997a7] AbstractPlotting v0.9.5
  [7d9fca2a] Arpack v0.3.0
  [13072b0f] AxisAlgorithms v0.3.0
  [39de3d68] AxisArrays v0.3.0
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.3
  [631607c0] CMake v1.1.1
  [d5fb7624] CMakeWrapper v0.2.2
  [336ed68f] CSV v0.4.3
  [49dc2e85] Calculus v0.4.1
  [aafaddc9] CatIndices v0.2.0
  [324d7699] CategoricalArrays v0.5.2
  [944b1d66] CodecZlib v0.5.2
  [a2cac450] ColorBrewer v0.4.0
  [3da002f7] ColorTypes v0.7.5
  [c3611d14] ColorVectorSpace v0.6.2
  [5ae59095] Colors v0.9.5
  [861a8166] Combinatorics v0.7.0
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v1.5.1
  [ed09eef8] ComputationalResources v0.3.0
  [8f4d0f93] Conda v1.2.0
  [d38c429a] Contour v0.5.1
  [150eb455] CoordinateTransformations v0.5.0
  [dc8bdbbb] CustomUnitRanges v0.2.0
  [a93c6f00] DataFrames v0.17.1
  [9a8bc11e] DataStreams v0.4.1
  [864edb3b] DataStructures v0.15.0
  [01453d9d] DiffEqDiffTools v0.8.0
  [163ba53b] DiffResults v0.0.4
  [b552c78f] DiffRules v0.0.10
  [b4f34e82] Distances v0.8.0
  [31c24e10] Distributions v0.16.4
  [ffbed154] DocStringExtensions v0.6.0
  [e30172f5] Documenter v0.21.5
  [8f5d6c58] EzXML v0.9.1
  [4f61f5a4] FFTViews v0.2.0
  [7a1cc6ca] FFTW v0.2.4
  [5789e2e9] FileIO v1.0.5
  [53c48c17] FixedPointNumbers v0.5.3
  [f6369f11] ForwardDiff v0.10.3
  [b38be410] FreeType v2.1.1
  [663a7486] FreeTypeAbstraction v0.4.2
  [da1fdf0e] FreqTables v0.3.1
  [add2ef01] GDAL v0.2.0
  [f7f18e0c] GLFW v2.3.0
  [e9467ef8] GLMakie v0.0.4
  [4d00f742] GeometryTypes v0.7.2
  [a2bd30eb] Graphics v0.4.0
  [d9be37ee] Homebrew v0.7.1
  [bbac6d45] IdentityRanges v0.3.0
  [2803e5a7] ImageAxes v0.5.0
  [a09fc81d] ImageCore v0.7.4
  [6a3955dd] ImageFiltering v0.5.3
  [6218d12a] ImageMagick v0.7.1
  [02fcd773] ImageTransformations v0.7.2
  [9b13fd28] IndirectArrays v0.5.0
  [a98d9a8b] Interpolations v0.11.2
  [8197267c] IntervalSets v0.3.1
  [c8e1da08] IterTools v1.1.1
  [82899510] IteratorInterfaceExtensions v0.1.1
  [682c06a0] JSON v0.20.0
  [5ab0869b] KernelDensity v0.5.1
  [d3d80556] LineSearches v7.0.1
  [4345ca2d] Loess v0.5.0
  [1914dd2f] MacroTools v0.4.5
  [ee78f7c6] Makie v0.9.2 #master (https://github.com/JuliaPlots/Makie.jl.git)
  [dbd62bd0] MakieGallery v0.0.4
  [dbb5928d] MappedArrays v0.2.1
  [7269a6da] MeshIO v0.3.1
  [e1d29d7a] Missings v0.4.0
  [78c3b35d] Mocking v0.5.7
  [66fc600b] ModernGL v1.0.0
  [d41bc354] NLSolversBase v7.3.1
  [77ba4419] NaNMath v0.3.2
  [86f7a689] NamedArrays v0.9.2
  [4d1e1d77] Nullables v0.0.8
  [510215fc] Observables v0.2.3
  [6fe1bfb0] OffsetArrays v0.10.0
  [429524aa] Optim v0.17.2
  [bac558e1] OrderedCollections v1.0.2
  [90014a1f] PDMats v0.9.6
  [19eb6ba3] Packing v0.3.0
  [5432bcbf] PaddedViews v0.4.2
  [d96e819e] Parameters v0.10.3
  [69de0a69] Parsers v0.2.18
  [995b91a9] PlotUtils v0.5.5
  [f27b6e38] Polynomials v0.5.2
  [85a6dd25] PositiveFactorizations v0.2.1
  [27ebfcd6] Primes v0.4.0
  [1fd47b50] QuadGK v2.0.3
  [dca85d43] QuartzImageIO v0.5.2
  [df47a6cb] RData v0.6.0
  [ce6b1742] RDatasets v0.6.1
  [b3c3ace0] RangeArrays v0.3.1
  [c84ed2f1] Ratios v0.3.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [79098fc4] Rmath v0.5.0
  [6038ab10] Rotations v0.11.1
  [992d4aef] Showoff v0.2.1
  [73760f76] SignedDistanceFields v0.4.0
  [699a6c99] SimpleTraits v0.8.0
  [a2af1166] SortingAlgorithms v0.3.1
  [276daf66] SpecialFunctions v0.7.2
  [90137ffa] StaticArrays v0.10.3
  [2913bbd2] StatsBase v0.28.1
  [4c63d2b9] StatsFuns v0.8.0
  [65254759] StatsMakie v0.0.2
  [09ab397b] StructArrays v0.2.1
  [3783bdb8] TableTraits v0.4.1
  [bd369af6] Tables v0.1.17
  [06e1c1a7] TiledIteration v0.2.3
  [f269a46b] TimeZones v0.8.5
  [3bb67fe8] TranscodingStreams v0.8.1
  [30578b45] URIParser v0.4.0
  [1cfade01] UnicodeFun v0.4.0
  [81def892] VersionParsing v1.1.3
  [ea10d353] WeakRefStrings v0.5.7
  [cc8bc4a8] Widgets v0.5.0
  [efce3f68] WoodburyMatrices v0.4.1
  [a5390f91] ZipFile v0.8.0
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [9fa8497b] Future  [`@stdlib/Future`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [9abbd945] Profile  [`@stdlib/Profile`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [4607b0f0] SuiteSparse  [`@stdlib/SuiteSparse`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
running tutorial_simple_scatter
running tutorial_markersize
running tutorial_simple_line
running tutrunning tutorial_simple_scatter
running tutorial_markersize
running tutorial_simple_line
running tutorial_adding_to_a_scene
running tutorial_adjusting_scene_limits
running tutorial_basic_theming
running tutorial_heatmap
running tutorial_linesegments
running tutorial_barplot
running test_heatmap___image_overlap
running animation
running barplot_1
running quiver_1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 54961  100 54961    0     0   175k      0 --:--:-- --:--:-- --:--:--  175k
running image_1
running scatter_colormap
running lots_of_heatmaps
running fem_polygon_2d
running fem_mesh_2d
running colored_triangle
running heatmap_interpolation
running colored_triangle_1
running subscenes
running polygons
running contour_function
running hbox_1
running customize_axes
running contour_1
running heatmap_1
running animated_scatter
running text_annotation
running text_rotation
running the_famous_iris_example
running chess_game
running parallel_prefix_sum
Scene (500px, 500px):
events:
    window_area: GeometryTypes.HyperRectangle{2,Int64}([0, 0], [0, 0])
    window_dpi: 100.0
    window_open: false
    mousebuttons: Set(AbstractPlotting.Mouse.Button[])
    mouseposition: (0.0, 0.0)
    mousedrag: notpressed
    scroll: (0.0, 0.0)
    keyboardbuttons: Set(AbstractPlotting.Keyboard.Button[])
    unicode_input: Char[]
    dropped_files: String[]
    hasfocus: false
    entered_window: false
plots:
   *Axis3D{...}
   *Mesh{...}
subscenes:running orthographic_camera
running volume_function
running textured_mesh
running load_mesh
running colored_mesh
running wireframe_of_a_mesh
running wireframe_of_sphere
running wireframe_of_a_surface
running surface_1
running surface_with_image
running line_function
running meshscatter_function
ERROR: LoadError: MethodError: no method matching light_calc(::Observables.Observable{Bool})
Closest candidates are:
  light_calc(!Matched::Bool) at ~/.julia/packages/GLMakie/rAuGK/src/GLVisualize/visualize/surface.jl:53
Stacktrace:
 [1] meshparticle(::Tuple{Observables.Observable{GeometryTypes.HyperSphere{3,Float32}},Observables.Observable{Array{Point{3,Float32},1}}}, ::GLMakie.GLAbstraction.Style{:default}, ::Dict{Symbol,Any}) at ~/.julia/packages/GLMakie/rAuGK/src/GLAbstraction/GLUtils.jl:179
 [2] _default(::Tuple{Observables.Observable{GeometryTypes.HyperSphere{3,Float32}},Observables.Observable{Array{Point{3,Float32},1}}}, ::GLMakie.GLAbstraction.Style{:default}, ::Dict{Symbol,Any}) at ~/.julia/packages/GLMakie/rAuGK/src/GLVisualize/visualize/particles.jl:188
 [3] default(::Any, ::Any, ::Any) at ~/.julia/packages/GLMakie/rAuGK/src/GLVisualize/visualize_interface.jl:4
 [4] visualize(::Any, ::GLMakie.GLAbstraction.Style{:default}, ::Dict{Symbol,Any}) at ~/.julia/packages/GLMakie/rAuGK/src/GLVisualize/visualize_interface.jl:21
 [5] (::getfield(GLMakie, Symbol("##61#63")){Scene,MeshScatter{...}})(::Dict{Symbol,Any}) at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:123
 [6] (::getfield(GLMakie, Symbol("##47#50")){getfield(GLMakie, Symbol("##61#63")){Scene,MeshScatter{...}},GLMakie.Screen,Scene,MeshScatter{...}})() at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:40
 [7] get!(::getfield(GLMakie, Symbol("##47#50")){getfield(GLMakie, Symbol("##61#63")){Scene,MeshScatter{...}},GLMakie.Screen,Scene,MeshScatter{...}}, ::Dict{UInt64,GLMakie.GLAbstraction.RenderObject}, ::UInt64) at ./dict.jl:453
 [8] cached_robj!(::getfield(GLMakie, Symbol("##61#63")){Scene,MeshScatter{...}}, ::GLMakie.Screen, ::Scene, ::MeshScatter{...}) at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:33
 [9] draw_atomic at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:112 [inlined]
 [10] insert!(::GLMakie.Screen, ::Scene, ::MeshScatter{...}) at ~/.julia/packages/GLMakie/rAuGK/src/drawing_primitives.jl:105
 [11] insertplots!(::GLMakie.Screen, ::Scene) at ~/.julia/packages/GLMakie/rAuGK/src/screen.jl:51
 [12] display(::GLMakie.Screen, ::Scene) at ~/.julia/packages/GLMakie/rAuGK/src/screen.jl:89
 [13] scene2image at ~/.julia/packages/GLMakie/rAuGK/src/gl_backend.jl:64 [inlined]
 [14] backend_show at ~/.julia/packages/GLMakie/rAuGK/src/gl_backend.jl:69 [inlined]
 [15] show(::IOContext{IOStream}, ::MIME{Symbol("image/png")}, ::Scene) at ~/.julia/packages/AbstractPlotting/KIwn9/src/display.jl:62
 [16] #689 at ~/.julia/packages/AbstractPlotting/KIwn9/src/display.jl:125 [inlined]
 [17] #open#310(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(AbstractPlotting, Symbol("##689#690")){Scene}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:369
 [18] open at ./iostream.jl:367 [inlined]
 [19] save at ~/.julia/packages/AbstractPlotting/KIwn9/src/display.jl:124 [inlined]
 [20] save_media at ~/.julia/packages/MakieGallery/ioVlA/src/io.jl:3 [inlined]
 [21] (::getfield(MakieGallery, Symbol("##99#101")){Tuple{Int64,Int64},String})(::MakieGallery.CellEntry, ::Scene) at ~/.julia/packages/MakieGallery/ioVlA/src/io.jl:221
 [22] (::getfield(MakieGallery, Symbol("##78#79")){Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#100")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#100")){String}}}},getfield(MakieGallery, Symbol("##99#101")){Tuple{Int64,Int64},String}})(::MakieGallery.CellEntry) at ~/.julia/packages/MakieGallery/ioVlA/src/database.jl:551
 [23] #enumerate_examples#61(::Int64, ::Nothing, ::Function, ::getfield(MakieGallery, Symbol("##78#79")){Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#100")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#100")){String}}}},getfield(MakieGallery, Symbol("##99#101")){Tuple{Int64,Int64},String}}) at ~/.julia/packages/MakieGallery/ioVlA/src/database.jl:498
 [24] #enumerate_examples at ./none:0 [inlined]
 [25] #eval_examples#77 at ~/.julia/packages/MakieGallery/ioVlA/src/database.jl:549 [inlined]
 [26] #eval_examples at ./none:0 [inlined]
 [27] #record_examples#98(::Tuple{Int64,Int64}, ::Bool, ::Bool, ::Function, ::String) at ~/.julia/packages/MakieGallery/ioVlA/src/io.jl:214
 [28] record_examples(::String) at ~/.julia/packages/MakieGallery/ioVlA/src/io.jl:198
 [29] top-level scope at none:0
 [30] include at ./boot.jl:326 [inlined]
 [31] include_relative(::Module, ::String) at ./loading.jl:1038
 [32] include(::Module, ::String) at ./sysimg.jl:29
 [33] include(::String) at ./client.jl:403
 [34] top-level scope at none:0
in expression starting at ~/.julia/packages/Makie/6qGoc/test/runtests.jl:20
ERROR: Package Makie errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:120
 [2] #test#66(::Bool, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1328
 [3] #test at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:0 [inlined]
 [4] #test#44(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:193
 [5] test at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:178 [inlined]
 [6] #test#43 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:175 [inlined]
 [7] test at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:175 [inlined]
 [8] #test#42 at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:174 [inlined]
 [9] test at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:174 [inlined]
 [10] #test#41(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:173
 [11] test(::String) at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:173
 [12] top-level scope at none:0
```

**Comment by SimonDanisch** [comment]
Ah damn, yeah, GLMakie needs to be on master with the newest AbstractPlotting :'(

**Comment by myrddin89** [comment]
Oh I see. This time the tests passed. Thanks for the help!

Closing.
