### ISSUE TITLE
test Makie fails on 1.2.0-rc2 on Linux

### ISSUE THREAD

**Issue by grahamas** [JuliaPlots/Makie.jl#372]
The simple solution `add GeometryTypes` doesn't change anything.

```
(v1.2) pkg> add Makie#master AbstractPlotting#master GLMakie#master
(...)
(v1.2) pkg> test Makie
   Testing Makie
 Resolving package versions...
    Status `/tmp/jl_Lfc4DE/Manifest.toml`
  [621f4979] AbstractFFTs v0.4.1
  [537997a7] AbstractPlotting v0.9.8 #master (https://github.com/JuliaPlots/AbstractPlotting.jl.git)
  [ec485272] ArnoldiMethod v0.0.4
  [7d9fca2a] Arpack v0.3.1
  [4fba245c] ArrayInterface v0.1.1
  [13072b0f] AxisAlgorithms v1.0.0
  [39de3d68] AxisArrays v0.3.0
  [aae01518] BandedMatrices v0.9.3
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.6
  [8e7c35d0] BlockArrays v0.9.1
  [ffab5731] BlockBandedMatrices v0.4.4
  [764a87c0] BoundaryValueDiffEq v2.2.3
  [631607c0] CMake v1.1.2
  [d5fb7624] CMakeWrapper v0.2.3
  [00ebfdb7] CSTParser v0.6.0
  [336ed68f] CSV v0.5.9
  [49dc2e85] Calculus v0.4.1
  [7057c7e9] Cassette v0.2.5
  [aafaddc9] CatIndices v0.2.0
  [324d7699] CategoricalArrays v0.5.4
  [944b1d66] CodecZlib v0.5.2
  [a2cac450] ColorBrewer v0.4.0
  [35d6a980] ColorSchemes v3.3.0
  [3da002f7] ColorTypes v0.8.0
  [c3611d14] ColorVectorSpace v0.6.2
  [5ae59095] Colors v0.9.5
  [861a8166] Combinatorics v0.7.0
  [bbf7d656] CommonSubexpressions v0.2.0
  [34da2185] Compat v2.1.0
  [ed09eef8] ComputationalResources v0.3.0
  [8f4d0f93] Conda v1.3.0
  [d38c429a] Contour v0.5.1
  [150eb455] CoordinateTransformations v0.5.0
  [a8cc5b0e] Crayons v4.0.0
  [dc8bdbbb] CustomUnitRanges v0.2.0
  [a93c6f00] DataFrames v0.19.0
  [864edb3b] DataStructures v0.17.0
  [e2d170a0] DataValueInterfaces v1.0.0
  [bcd4f6db] DelayDiffEq v5.8.0
  [2b5f629d] DiffEqBase v5.16.4
  [459566f4] DiffEqCallbacks v2.5.2
  [01453d9d] DiffEqDiffTools v0.14.0
  [5a0ffddc] DiffEqFinancial v2.1.0
  [c894b116] DiffEqJump v6.1.1
  [77a26b50] DiffEqNoiseProcess v3.3.1
  [9fdde737] DiffEqOperators v3.5.0
  [055956cb] DiffEqPhysics v3.2.0
  [163ba53b] DiffResults v0.0.4
  [b552c78f] DiffRules v0.0.10
  [0c46a032] DifferentialEquations v6.6.0
  [c619ae07] DimensionalPlotRecipes v0.2.0
  [b4f34e82] Distances v0.8.0
  [31c24e10] Distributions v0.19.2
  [ffbed154] DocStringExtensions v0.7.0
  [e30172f5] Documenter v0.22.5
  [d4d017d3] ExponentialUtilities v1.5.1
  [8f5d6c58] EzXML v0.9.3
  [c87230d0] FFMPEG v0.2.1
  [4f61f5a4] FFTViews v0.2.0
  [7a1cc6ca] FFTW v0.2.4
  [5789e2e9] FileIO v1.0.7
  [1a297f60] FillArrays v0.6.3
  [53c48c17] FixedPointNumbers v0.5.3
  [f6369f11] ForwardDiff v0.10.3
  [b38be410] FreeType v2.1.1
  [663a7486] FreeTypeAbstraction v0.4.2
  [da1fdf0e] FreqTables v0.3.1
  [069b7b12] FunctionWrappers v1.0.0
  [add2ef01] GDAL v0.2.0
  [f7f18e0c] GLFW v2.3.0
  [e9467ef8] GLMakie v0.0.7 #master (https://github.com/JuliaPlots/GLMakie.jl.git)
  [01680d73] GenericSVD v0.2.1
  [4d00f742] GeometryTypes v0.7.5
  [a2bd30eb] Graphics v0.4.0
  [d9be37ee] Homebrew v0.7.1
  [7869d1d1] IRTools v0.2.2
  [bbac6d45] IdentityRanges v0.3.0
  [2803e5a7] ImageAxes v0.6.0
  [a09fc81d] ImageCore v0.8.4
  [6a3955dd] ImageFiltering v0.6.3
  [6218d12a] ImageMagick v0.7.5
  [02fcd773] ImageTransformations v0.8.0
  [9b13fd28] IndirectArrays v0.5.0
  [d25df0c9] Inflate v0.1.1
  [a98d9a8b] Interpolations v0.12.2
  [8197267c] IntervalSets v0.3.1
  [41ab1584] InvertedIndices v1.0.0
  [c8e1da08] IterTools v1.2.0
  [42fd0dbc] IterativeSolvers v0.8.1
  [82899510] IteratorInterfaceExtensions v1.0.0
  [682c06a0] JSON v0.20.0
  [5ab0869b] KernelDensity v0.5.1
  [5078a376] LazyArrays v0.9.0
  [093fc24a] LightGraphs v1.2.0
  [d3d80556] LineSearches v7.0.1
  [4345ca2d] Loess v0.5.0
  [1914dd2f] MacroTools v0.5.1
  [ee78f7c6] Makie v0.9.4 #master (https://github.com/JuliaPlots/Makie.jl.git)
  [dbd62bd0] MakieGallery v0.0.9
  [dbb5928d] MappedArrays v0.2.1
  [a3b82374] MatrixFactorizations v0.0.4
  [7269a6da] MeshIO v0.3.1
  [e1d29d7a] Missings v0.4.1
  [78c3b35d] Mocking v0.5.7
  [66fc600b] ModernGL v1.0.0
  [46d2c3a1] MuladdMacro v0.2.1
  [f9640e96] MultiScaleArrays v1.4.0
  [d41bc354] NLSolversBase v7.3.1
  [2774e3e8] NLsolve v4.0.0
  [872c559c] NNlib v0.6.0
  [77ba4419] NaNMath v0.3.2
  [86f7a689] NamedArrays v0.9.3
  [510215fc] Observables v0.2.3
  [6fe1bfb0] OffsetArrays v0.11.1
  [429524aa] Optim v0.19.1
  [bac558e1] OrderedCollections v1.1.0
  [1dea7af3] OrdinaryDiffEq v5.12.0
  [90014a1f] PDMats v0.9.7
  [19eb6ba3] Packing v0.3.0
  [5432bcbf] PaddedViews v0.4.2
  [65888b18] ParameterizedFunctions v4.2.0
  [d96e819e] Parameters v0.10.3
  [69de0a69] Parsers v0.3.6
  [995b91a9] PlotUtils v0.5.8
  [e409e4f3] PoissonRandom v0.4.0
  [f27b6e38] Polynomials v0.5.2
  [2dfb63ee] PooledArrays v0.5.2
  [85a6dd25] PositiveFactorizations v0.2.2
  [1fd47b50] QuadGK v2.0.3
  [df47a6cb] RData v0.6.2
  [ce6b1742] RDatasets v0.6.1
  [e6cf234a] RandomNumbers v1.3.0
  [b3c3ace0] RangeArrays v0.3.1
  [c84ed2f1] Ratios v0.3.1
  [3cdcf5f2] RecipesBase v0.7.0
  [731186ca] RecursiveArrayTools v0.20.0
  [f2c3362d] RecursiveFactorization v0.1.0
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v0.5.2
  [ae5879a3] ResettableStacks v0.6.0
  [79098fc4] Rmath v0.5.0
  [f2b01f46] Roots v0.8.1
  [6038ab10] Rotations v0.11.1
  [992d4aef] Showoff v0.3.1
  [73760f76] SignedDistanceFields v0.4.0
  [699a6c99] SimpleTraits v0.8.0
  [a2af1166] SortingAlgorithms v0.3.1
  [47a9eef4] SparseDiffTools v0.4.0
  [276daf66] SpecialFunctions v0.7.2
  [90137ffa] StaticArrays v0.11.0
  [2913bbd2] StatsBase v0.31.0
  [4c63d2b9] StatsFuns v0.8.0
  [65254759] StatsMakie v0.0.6
  [9672c7b4] SteadyStateDiffEq v1.5.0
  [789caeaf] StochasticDiffEq v6.6.0
  [09ab397b] StructArrays v0.4.0
  [c3572dad] Sundials v3.6.1
  [123dc426] SymEngine v0.7.0
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v0.2.9
  [06e1c1a7] TiledIteration v0.2.3
  [f269a46b] TimeZones v0.9.1
  [a759f4b9] TimerOutputs v0.5.0
  [0796e94c] Tokenize v0.5.5
  [3bb67fe8] TranscodingStreams v0.9.4
  [a2a6695c] TreeViews v0.3.0
  [30578b45] URIParser v0.4.0
  [1cfade01] UnicodeFun v0.4.0
  [81def892] VersionParsing v1.1.3
  [19fa3120] VertexSafeGraphs v0.1.0
  [ea10d353] WeakRefStrings v0.6.1
  [cc8bc4a8] Widgets v0.6.1
  [efce3f68] WoodburyMatrices v0.4.1
  [a5390f91] ZipFile v0.8.3
  [e88e6eb3] Zygote v0.3.2
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8bb1440f] DelimitedFiles  [`@stdlib/DelimitedFiles`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [9fa8497b] Future  [`@stdlib/Future`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [9abbd945] Profile  [`@stdlib/Profile`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [1a1011a3] SharedArrays  [`@stdlib/SharedArrays`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [10745b16] Statistics  [`@stdlib/Statistics`]
  [4607b0f0] SuiteSparse  [`@stdlib/SuiteSparse`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
WARNING: using GLAbstraction.update! in module GLMakie conflicts with an existing identifier.
WARNING: using Makie.AbstractPlotting in module Main conflicts with an existing identifier.
[ Info: starting from index 1
Running tutorial_simple_scatter
Running tutorial_markersize
Running tutorial_simple_line
Running tutorial_adding_to_a_scene
Running tutorial_adjusting_scene_limits
Running tutorial_basic_theming
Running tutorial_heatmap
Running tutorial_linesegments
Running tutorial_barplot
Running tutorial_title
Running animated_time_series
Running test_heatmap___image_overlap
Running animation
Running barplot_1
Running poly_and_colormap
Running quiver_1
Running image_1
Running scatter_colormap
Running lots_of_heatmaps
Running fem_polygon_2d
Running fem_mesh_2d
Running colored_triangle
Running heatmap_interpolation
Running colored_triangle_1
Running subscenes
Example Polygons failed with source:
    using AbstractPlotting, Makie
     using GeometryTypes
    
         scene = Scene(resolution = (500, 500))
         points = decompose(Point2f0, Circle(Point2f0(50), 50f0))
         pol = poly!(scene, points, color = :gray, strokewidth = 10, strokecolor = :red)
         # Optimized forms
         poly!(scene, [Circle(Point2f0(50+300), 50f0)], color = :gray, strokewidth = 10, strokecolor = :red)
         poly!(scene, [Circle(Point2f0(50+i, 50+i), 10f0) for i = 1:100:400], color = :red)
         poly!(scene, [Rectangle{Float32}(50+i, 50+i, 20, 20) for i = 1:100:400], strokewidth = 2, strokecolor = :green)
         linesegments!(scene,
             [Point2f0(50 + i, 50 + i) => Point2f0(i + 70, i + 70) for i = 1:100:400], linewidth = 8, color = :purple
         )
        
    
Full Gallery recording: Error During Test at /home/grahams/.julia/packages/MakieGallery/CpvaL/src/io.jl:227
  Got exception outside of a @test
  LoadError: ArgumentError: Package GeometryTypes not found in current path:
  - Run `import Pkg; Pkg.add("GeometryTypes")` to install the GeometryTypes package.
  
  Stacktrace:
   [1] require(::Module, ::Symbol) at ./loading.jl:876
   [2] include_string(::Module, ::String, ::String) at ./loading.jl:1064
   [3] #eval_example#74(::Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#104")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#104")){String}}}}, ::typeof(eval_example), ::MakieGallery.CellEntry) at /home/grahams/.julia/packages/MakieGallery/CpvaL/src/database.jl:542
   [4] #eval_example at ./none:0 [inlined]
   [5] (::getfield(MakieGallery, Symbol("##78#79")){Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#104")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#104")){String}}}},getfield(MakieGallery, Symbol("##103#105")){Tuple{Int64,Int64},String,Array{Any,1}}})(::MakieGallery.CellEntry) at /home/grahams/.julia/packages/MakieGallery/CpvaL/src/database.jl:571
   [6] #enumerate_examples#61(::Int64, ::Nothing, ::typeof(MakieGallery.enumerate_examples), ::getfield(MakieGallery, Symbol("##78#79")){Base.Iterators.Pairs{Symbol,getfield(MakieGallery, Symbol("#output_path#104")){String},Tuple{Symbol},NamedTuple{(:outputfile,),Tuple{getfield(MakieGallery, Symbol("#output_path#104")){String}}}},getfield(MakieGallery, Symbol("##103#105")){Tuple{Int64,Int64},String,Array{Any,1}}}) at /home/grahams/.julia/packages/MakieGallery/CpvaL/src/database.jl:503
   [7] #enumerate_examples at ./none:0 [inlined]
   [8] #eval_examples#77 at /home/grahams/.julia/packages/MakieGallery/CpvaL/src/database.jl:570 [inlined]
   [9] #eval_examples at ./none:0 [inlined]
   [10] macro expansion at /home/grahams/.julia/packages/MakieGallery/CpvaL/src/io.jl:228 [inlined]
   [11] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113 [inlined]
   [12] #record_examples#102(::Tuple{Int64,Int64}, ::Bool, ::Bool, ::typeof(MakieGallery.record_examples), ::String) at /home/grahams/.julia/packages/MakieGallery/CpvaL/src/io.jl:228
   [13] record_examples(::String) at /home/grahams/.julia/packages/MakieGallery/CpvaL/src/io.jl:209
   [14] top-level scope at /home/grahams/.julia/packages/Makie/Ed00j/test/runtests.jl:12
   [15] include at ./boot.jl:328 [inlined]
   [16] include_relative(::Module, ::String) at ./loading.jl:1094
   [17] include(::Module, ::String) at ./Base.jl:31
   [18] include(::String) at ./client.jl:431
   [19] top-level scope at none:5
   [20] eval(::Module, ::Any) at ./boot.jl:330
   [21] exec_options(::Base.JLOptions) at ./client.jl:271
   [22] _start() at ./client.jl:464
  in expression starting at polygons:2
  
Test Summary:                     | Pass  Error  Total
Full Gallery recording            |   25      1     26
  Tutorial simple scatter         |    1             1
  Tutorial markersize             |    1             1
  Tutorial simple line            |    1             1
  Tutorial adding to a scene      |    1             1
  Tutorial adjusting scene limits |    1             1
  Tutorial basic theming          |    1             1
  Tutorial heatmap                |    1             1
  Tutorial linesegments           |    1             1
  Tutorial barplot                |    1             1
  Tutorial title                  |    1             1
  Animated time series            |    1             1
  Test heatmap + image overlap    |    1             1
  Animation                       |    1             1
  barplot                         |    1             1
  poly and colormap               |    1             1
  quiver                          |    1             1
  image                           |    1             1
  scatter colormap                |    1             1
  Lots of Heatmaps                |    1             1
  FEM polygon 2D                  |    1             1
  FEM mesh 2D                     |    1             1
  colored triangle                |    1             1
  heatmap interpolation           |    1             1
  colored triangle                |    1             1
  Subscenes                       |    1             1
ERROR: LoadError: Some tests did not pass: 25 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/grahams/.julia/packages/Makie/Ed00j/test/runtests.jl:12
ERROR: Package Makie errored during testing
```

**Comment by asinghvi17** [comment]
Could have to do with test reps.  Will take a closer look tomorrow.

**Comment by asinghvi17** [comment]
Should be fixed now.

**Comment by grahamas** [comment]
I still get the same error, but I also don't see any new commits so I might be missing something.
